import { StyleSheet } from "react-native";

export const COLORS = {
  bg: "#FFF6F7",
  primary: "#FF685E",
  text: "#333",
  subtext: "#888",
  card: "#FFFFFF",
  pill: "#FFF",
  border: "#E9E9EE",
  shadow: "rgba(0,0,0,0.08)",
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.bg },

  header: {
    height: 56,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerCenter: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtn: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    backgroundColor: COLORS.primary,
    borderRadius: 20,
  },
  saveText: { color: "#fff", fontWeight: "600", fontSize: 14 },

  container: { padding: 20 },
  title: { fontSize: 20, fontWeight: "700", marginBottom: 24, color: COLORS.text },

  // 프로필
  profileRow: { flexDirection: "row", alignItems: "center", marginBottom: 24 },
  avatarWrap: { position: "relative" },
  avatarCamera: {
    position: "absolute",
    bottom: 0,
    right: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  avatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: COLORS.card,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  avatarImage: {
    width: "75%",
    height: "75%",
    resizeMode: "contain",
  },

  label: { fontSize: 14, color: COLORS.text, marginBottom: 6, fontWeight: "800" },
  inputPill: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  inputText: { fontSize: 14, color: COLORS.text },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputRowFocused: {
    borderColor: COLORS.primary,
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },

  sectionLabel: { fontSize: 15, fontWeight: "800", color: COLORS.text, marginTop: 20, marginBottom: 10 },
  hint: { fontSize: 12, color: COLORS.subtext },

  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },

  selectPill: {
    backgroundColor: COLORS.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 6,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  selectText: { fontSize: 14, color: COLORS.text },

  modalDim: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 8,
    shadowColor: COLORS.shadow,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  modalItem: {
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderRadius: 8,
  },
  modalText: { fontSize: 15, color: COLORS.text },

  childHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 10,
  },
  addBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.card,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
});
